promotion: action

server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    initialization-mode: always
    platform: h2
    url: jdbc:h2:mem:mediadb;
    username: sa
    password: null
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update